server:
  port: ${SERVER_PORT:8761}

spring:
  application:
    name: discovery-service

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:${SERVER_PORT:8761}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false
  instance:
    hostname: localhost

logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO

    ?