server:
  port: 8084

#    eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true


  # gateway config
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/auth/login,/auth/generate-otp/**,/auth/verify-otp/**,/auth/validate-token/**,/user-roles/**,/auth/reset-password/**,/users/**
        - id: authentication-service-create-password
          uri: lb://authentication-service
          predicates:
            - Path=/auth/create-password,/auth/register/**,/departments/**,/roles/**
          filters:
            - name: AuthFilter
        - id: sops_service
          uri: lb://sop-management-service
          predicates:
            - Path=/sop-management/**
          filters:
            - name: AuthFilter
        - id: email_service
          uri: lb://email-service
          predicates:
            - Path=/email-service/**
        - id: notifications_service
          uri: lb://notifications-service
          predicates:
            - Path=/test/**
          filters:
            - AuthFilter

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /auth/v3/api-docs
        name: Authentication Service
      - url: /sop-management/v3/api-docs
        name: SOP Management Service
